// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTBTDqkBk5vsCLv_gW5nqeO2X_LjyR-A',
    appId: '1:415655545649:web:2a81387e9b48a813543e10',
    messagingSenderId: '415655545649',
    projectId: 'register-afe35',
    authDomain: 'register-afe35.firebaseapp.com',
    storageBucket: 'register-afe35.firebasestorage.app',
    measurementId: 'G-SCZT181VB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAY7b6Gh-Om2gbEELcxUwpE7qjn3x8roI',
    appId: '1:415655545649:android:aa71f80d6d6c0767543e10',
    messagingSenderId: '415655545649',
    projectId: 'register-afe35',
    storageBucket: 'register-afe35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWtZejjNol1cxo03eeldRGZYK_2R8CA0',
    appId: '1:415655545649:ios:7b6a5fda36006708543e10',
    messagingSenderId: '415655545649',
    projectId: 'register-afe35',
    storageBucket: 'register-afe35.firebasestorage.app',
    iosBundleId: 'com.example.regestrationAppflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqWtZejjNol1cxo03eeldRGZYK_2R8CA0',
    appId: '1:415655545649:ios:7b6a5fda36006708543e10',
    messagingSenderId: '415655545649',
    projectId: 'register-afe35',
    storageBucket: 'register-afe35.firebasestorage.app',
    iosBundleId: 'com.example.regestrationAppflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoTBTDqkBk5vsCLv_gW5nqeO2X_LjyR-A',
    appId: '1:415655545649:web:56a5665abb211fdd543e10',
    messagingSenderId: '415655545649',
    projectId: 'register-afe35',
    authDomain: 'register-afe35.firebaseapp.com',
    storageBucket: 'register-afe35.firebasestorage.app',
    measurementId: 'G-DW1CR0D9VK',
  );
}
